#!/usr/bin/env bash
# {{{frameworkTitle}}} — Local Install
# Generated by @forwardimpact/pathway v{{{version}}}
#
# Installs fit-pathway globally via bun and downloads organization data
# to ~/.fit/data/pathway/.
#
# Usage:
#   curl -fsSL {{{siteUrl}}}/install.sh | bash
#
set -euo pipefail

SITE_URL="{{{siteUrl}}}"
INSTALL_DIR="${HOME}/.fit/data/pathway"

command -v bun >/dev/null 2>&1 || { echo "Error: Bun 1.2+ is required. https://bun.sh"; exit 1; }

# Install fit-pathway globally (provides the fit-pathway binary on PATH)
echo "Installing @forwardimpact/pathway globally..."
bun install -g @forwardimpact/pathway@{{{version}}}

# Download organization data to ~/.fit/data/pathway/
echo "Downloading organization data to ${INSTALL_DIR}..."
mkdir -p "${INSTALL_DIR}"

TMPDIR_INSTALL=$(mktemp -d)
trap 'rm -rf "$TMPDIR_INSTALL"' EXIT
curl -fsSL "${SITE_URL}/bundle.tar.gz" -o "${TMPDIR_INSTALL}/bundle.tar.gz"
tar -xzf "${TMPDIR_INSTALL}/bundle.tar.gz" -C "${TMPDIR_INSTALL}" --strip-components=1
cp -R "${TMPDIR_INSTALL}/data/." "${INSTALL_DIR}/"
cp "${TMPDIR_INSTALL}/package.json" "${HOME}/.fit/data/package.json" 2>/dev/null || true

echo ""
echo "Done. Usage:"
echo "  fit-pathway skill --list"
echo "  fit-pathway job --list"
echo "  fit-pathway agent --list"
