#!/usr/bin/env bash
# {{{frameworkTitle}}} — Local Install
# Generated by @forwardimpact/pathway v{{{version}}}
#
# Installs to ~/.fit/pathway/
#
# Usage:
#   curl -fsSL {{{siteUrl}}}/install.sh | bash
#
set -euo pipefail

SITE_URL="{{{siteUrl}}}"
INSTALL_DIR="${HOME}/.fit/pathway"

command -v node >/dev/null 2>&1 || { echo "Error: Node.js 18+ is required. https://nodejs.org"; exit 1; }
command -v npm  >/dev/null 2>&1 || { echo "Error: npm is required."; exit 1; }

echo "Installing to ${INSTALL_DIR}..."
mkdir -p "${INSTALL_DIR}"

TMPFILE=$(mktemp)
trap 'rm -f "$TMPFILE"' EXIT
curl -fsSL "${SITE_URL}/bundle.tar.gz" -o "$TMPFILE"
tar -xzf "$TMPFILE" -C "${INSTALL_DIR}" --strip-components=1

(cd "${INSTALL_DIR}" && npm install --production --ignore-scripts --no-audit --no-fund --silent)

echo ""
echo "Done. Usage:"
echo "  cd ${INSTALL_DIR}"
echo "  npx fit-pathway skill --list"
echo "  npx fit-pathway job --list"
echo "  npx fit-pathway agent --list"
