#!/usr/bin/env bash
# {{{frameworkTitle}}} — Local Install
# Generated by @forwardimpact/pathway v{{{version}}}
#
# Installs fit-pathway globally via bun and downloads organization data
# to ~/.fit/pathway/data/.
#
# Usage:
#   curl -fsSL {{{siteUrl}}}/install.sh | bash
#
set -euo pipefail

SITE_URL="{{{siteUrl}}}"
INSTALL_DIR="${HOME}/.fit/pathway"

command -v bun >/dev/null 2>&1 || { echo "Error: Bun 1.2+ is required. https://bun.sh"; exit 1; }

# Install fit-pathway globally (provides the fit-pathway binary on PATH)
echo "Installing @forwardimpact/pathway globally..."
bun install -g @forwardimpact/pathway@{{{version}}}

# Download organization data to ~/.fit/pathway/data/
echo "Downloading organization data to ${INSTALL_DIR}/data/..."
mkdir -p "${INSTALL_DIR}"

TMPFILE=$(mktemp)
trap 'rm -f "$TMPFILE"' EXIT
curl -fsSL "${SITE_URL}/bundle.tar.gz" -o "$TMPFILE"
tar -xzf "$TMPFILE" -C "${INSTALL_DIR}" --strip-components=1

echo ""
echo "Done. Usage:"
echo "  fit-pathway skill --list"
echo "  fit-pathway job --list"
echo "  fit-pathway agent --list"
