import js from "@eslint/js";
import prettierConfig from "eslint-config-prettier";
import security from "eslint-plugin-security";

export default [
  js.configs.recommended,
  security.configs.recommended,
  prettierConfig,
  {
    rules: {
      "no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      "no-console": "off",
      "max-lines": [
        "error",
        { max: 400, skipBlankLines: true, skipComments: true },
      ],
      complexity: ["error", 14],
      "security/detect-buffer-noassert": "error",
      "security/detect-child-process": "error",
      "security/detect-disable-mustache-escape": "error",
      "security/detect-eval-with-expression": "error",
      "security/detect-new-buffer": "error",
      "security/detect-no-csrf-before-method-override": "error",
      "security/detect-non-literal-regexp": "error",
      "security/detect-non-literal-require": "error",
      "security/detect-object-injection": "off",
      "security/detect-non-literal-fs-filename": "off",
      "security/detect-possible-timing-attacks": "error",
      "security/detect-pseudoRandomBytes": "error",
      "security/detect-unsafe-regex": "error",
      "security/detect-bidi-characters": "error",
    },
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        console: "readonly",
        process: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        document: "readonly",
        window: "readonly",
        fetch: "readonly",
        customElements: "readonly",
        HTMLElement: "readonly",
        history: "readonly",
        location: "readonly",
        localStorage: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        AbortController: "readonly",
        Blob: "readonly",
        ClipboardItem: "readonly",
        confirm: "readonly",
        navigator: "readonly",
        requestAnimationFrame: "readonly",
        IntersectionObserver: "readonly",
      },
    },
  },
  {
    files: ["products/outpost/**/*.js", "products/outpost/**/*.mjs"],
    languageOptions: {
      globals: {
        Bun: "readonly",
        Buffer: "readonly",
        clearTimeout: "readonly",
        Deno: "readonly",
        Response: "readonly",
        setInterval: "readonly",
        setTimeout: "readonly",
        require: "readonly",
        TextEncoder: "readonly",
        TextDecoder: "readonly",
      },
    },
    rules: {
      "no-empty": "off",
    },
  },
  {
    files: ["libraries/**/*.js", "services/**/*.js"],
    languageOptions: {
      globals: {
        global: "readonly",
        Buffer: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        clearTimeout: "readonly",
        TextEncoder: "readonly",
        TextDecoder: "readonly",
        structuredClone: "readonly",
        AbortController: "readonly",
        AbortSignal: "readonly",
        btoa: "readonly",
        atob: "readonly",
        EventTarget: "readonly",
        Event: "readonly",
        crypto: "readonly",
        performance: "readonly",
        Response: "readonly",
        Headers: "readonly",
        ReadableStream: "readonly",
        queueMicrotask: "readonly",
      },
    },
  },
  {
    ignores: [
      "node_modules/**",
      "tmp/**",
      "**/dist/**",
      "**/generated/**",
      "public/**",
    ],
  },
];
