import { test, expect } from "@playwright/test";

test("job builder can generate a job", async ({ page }) => {
  const errors = [];

  page.on("pageerror", (error) => {
    errors.push(error.message);
  });

  // Abort external requests (fonts, prism) that are non-essential
  await page.route(
    (url) => !url.hostname.includes("localhost"),
    (route) => route.abort(),
  );

  await page.goto("./#/job-builder", { waitUntil: "domcontentloaded" });

  // Page loads with the job builder form
  await expect(page.locator("h1")).toContainText("Job Builder");

  // Select discipline, level, track
  // Uses IDs from examples/ data generated by fit-universe
  await page.selectOption("#discipline-select", "software_engineering");
  await page.selectOption("#level-select", "J070");
  await page.selectOption("#track-select", "platform");

  // Verify preview appears with valid combination message
  await expect(page.locator(".job-preview")).toBeVisible();
  await expect(page.locator(".job-preview-valid")).toBeVisible();
  await expect(page.locator(".job-preview-title")).toContainText(
    "Software Engineer",
  );

  // Navigate to full job definition
  await page.click("#generate-btn");
  await expect(page.locator("h1")).toContainText("Software Engineer");

  // Check no JS errors occurred
  expect(errors).toEqual([]);
});
