/**
 * Questions YAML Formatter
 *
 * Formats questions as YAML for export and bulk editing.
 */

import { stringify } from "yaml";

/**
 * Format questions as YAML
 * @param {Object} view - Questions view from prepareQuestionsView
 * @param {Object} options - Format options
 * @returns {string}
 */
export function questionsToYaml(view, _options = {}) {
  const { filter, questions } = view;

  // Build header comment
  const filterParts = [];
  if (filter.level) filterParts.push(`--level=${filter.level}`);
  if (filter.maturity) filterParts.push(`--maturity=${filter.maturity}`);
  if (filter.skills) filterParts.push(`--skill=${filter.skills.join(",")}`);
  if (filter.behaviours)
    filterParts.push(`--behaviour=${filter.behaviours.join(",")}`);
  if (filter.capability) filterParts.push(`--capability=${filter.capability}`);

  const filterStr =
    filterParts.length > 0 ? filterParts.join(" ") : "(no filters)";
  const header = `# Generated by: npx pathway questions ${filterStr}\n# Questions: ${questions.length}\n\n`;

  // Group questions by source
  const bySource = {};
  for (const q of questions) {
    if (!bySource[q.source]) {
      bySource[q.source] = [];
    }

    // Build question object for YAML
    const yamlQuestion = {
      id: q.id,
      text: q.text,
      lookingFor: q.lookingFor,
      expectedDurationMinutes: q.expectedDurationMinutes,
    };

    if (q.followUps.length > 0) {
      yamlQuestion.followUps = q.followUps;
    }

    bySource[q.source].push({
      level: q.level,
      question: yamlQuestion,
    });
  }

  // Build output structure grouped by source then level
  const output = {};
  for (const [sourceId, items] of Object.entries(bySource).sort()) {
    output[sourceId] = {};
    for (const item of items) {
      if (!output[sourceId][item.level]) {
        output[sourceId][item.level] = [];
      }
      output[sourceId][item.level].push(item.question);
    }
  }

  // Stringify with nice formatting
  const yamlContent = stringify(output, {
    lineWidth: 80,
    defaultKeyType: "PLAIN",
    defaultStringType: "PLAIN",
  });

  return header + yamlContent;
}
