import { test, describe, before, after } from "node:test";
import assert from "node:assert";
import { mkdtempSync, rmSync, readFileSync } from "node:fs";
import { mkdir, readdir } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { tmpdir } from "node:os";

import { createDataLoader } from "@forwardimpact/map/loader";
import { generatePacks } from "../src/commands/build-packs.js";
import { findValidCombinations } from "../src/commands/agent.js";
import {
  getPackName,
  getRawCommand,
  getApmInstallCommand,
  getApmCommand,
  getSkillsCommand,
  getSkillsGitCommand,
  createInstallSection,
} from "../src/pages/agent-builder-install.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const starterDir = join(__dirname, "..", "..", "map", "starter");
const pathwayPkg = JSON.parse(
  readFileSync(join(__dirname, "..", "package.json"), "utf8"),
);

/**
 * Silence console.log for the duration of a callback. generatePacks logs
 * progress lines; tests don't need to see them.
 */
async function silent(fn) {
  const original = console.log;
  console.log = () => {};
  try {
    return await fn();
  } finally {
    console.log = original;
  }
}

describe("agent-builder-install", () => {
  describe("getPackName", () => {
    test("uses discipline abbreviation + kebab-case track id", () => {
      const discipline = { id: "software_engineering" };
      const track = { id: "platform" };
      // "se-platform" matches the name generated by build-packs.js
      assert.strictEqual(getPackName(discipline, track), "se-platform");
    });

    test("converts snake_case track id to kebab-case", () => {
      const discipline = { id: "data_engineering" };
      const track = { id: "infra_tools" };
      assert.strictEqual(getPackName(discipline, track), "de-infra-tools");
    });

    test("falls back to first two chars for unknown discipline", () => {
      const discipline = { id: "xenobiology" };
      const track = { id: "lab" };
      assert.strictEqual(getPackName(discipline, track), "xe-lab");
    });
  });

  describe("getRawCommand", () => {
    test("pipes download through tar for direct extraction", () => {
      assert.strictEqual(
        getRawCommand("https://example.com", "se-platform"),
        "curl -sL https://example.com/packs/se-platform.raw.tar.gz | tar xz",
      );
    });

    test("strips a trailing slash from the site URL", () => {
      assert.strictEqual(
        getRawCommand("https://example.com/", "se-platform"),
        "curl -sL https://example.com/packs/se-platform.raw.tar.gz | tar xz",
      );
    });
  });

  describe("getApmCommand", () => {
    test("downloads then unpacks the APM bundle", () => {
      assert.strictEqual(
        getApmCommand("https://example.com", "se-platform"),
        "curl -sLO https://example.com/packs/se-platform.apm.tar.gz && apm unpack se-platform.apm.tar.gz",
      );
    });

    test("strips a trailing slash from the site URL", () => {
      assert.strictEqual(
        getApmCommand("https://example.com/", "se-platform"),
        "curl -sLO https://example.com/packs/se-platform.apm.tar.gz && apm unpack se-platform.apm.tar.gz",
      );
    });
  });

  describe("getSkillsCommand", () => {
    test("points at the per-pack URL for well-known discovery", () => {
      assert.strictEqual(
        getSkillsCommand("https://example.com", "se-platform"),
        "npx skills add https://example.com/packs/se-platform",
      );
    });

    test("strips a trailing slash from the site URL", () => {
      assert.strictEqual(
        getSkillsCommand("https://example.com/", "se-platform"),
        "npx skills add https://example.com/packs/se-platform",
      );
    });
  });

  describe("getApmInstallCommand", () => {
    test("uses .apm.git URL for native apm install", () => {
      assert.strictEqual(
        getApmInstallCommand("https://example.com", "se-platform"),
        "apm install https://example.com/packs/se-platform.apm.git",
      );
    });

    test("strips a trailing slash from the site URL", () => {
      assert.strictEqual(
        getApmInstallCommand("https://example.com/", "se-platform"),
        "apm install https://example.com/packs/se-platform.apm.git",
      );
    });
  });

  describe("getSkillsGitCommand", () => {
    test("uses .skills.git URL for git clone", () => {
      assert.strictEqual(
        getSkillsGitCommand("https://example.com", "se-platform"),
        "git clone https://example.com/packs/se-platform.skills.git",
      );
    });

    test("strips a trailing slash from the site URL", () => {
      assert.strictEqual(
        getSkillsGitCommand("https://example.com/", "se-platform"),
        "git clone https://example.com/packs/se-platform.skills.git",
      );
    });
  });

  describe("createInstallSection", () => {
    // createInstallSection returns null for falsy siteUrl before touching
    // any DOM APIs, so this branch is safe to exercise in node. The
    // happy-path renders via `document.createElement`, which is covered
    // end-to-end by the Playwright suite rather than duplicated here.
    test("returns null when siteUrl is undefined", () => {
      const result = createInstallSection({
        discipline: { id: "software_engineering" },
        track: { id: "platform" },
        siteUrl: undefined,
      });
      assert.strictEqual(result, null);
    });

    test("returns null when siteUrl is an empty string", () => {
      const result = createInstallSection({
        discipline: { id: "software_engineering" },
        track: { id: "platform" },
        siteUrl: "",
      });
      assert.strictEqual(result, null);
    });
  });

  // Integration drift check: the pack name the UI displays must match the
  // archive filename actually emitted by build-packs.js. If either side
  // changes its naming formula, this test fails before users copy a broken
  // install command.
  describe("matches build-packs output for starter data", () => {
    let workDir;
    let outputDir;
    let combinations;

    before(async () => {
      workDir = mkdtempSync(join(tmpdir(), "fit-pathway-install-test-"));
      outputDir = join(workDir, "public");
      await mkdir(outputDir, { recursive: true });

      const loader = createDataLoader();
      const data = await loader.loadAllData(starterDir);
      const agentData = await loader.loadAgentData(starterDir);
      combinations = findValidCombinations(data, agentData);

      await silent(() =>
        generatePacks({
          outputDir,
          dataDir: starterDir,
          siteUrl: "https://example.test",
          standard: { title: "Engineering Pathway" },
          version: pathwayPkg.version,
          templatesDir: join(__dirname, "..", "templates"),
        }),
      );
    });

    after(() => {
      if (workDir) rmSync(workDir, { recursive: true, force: true });
    });

    test("every valid combination's getPackName matches an emitted archive", async () => {
      assert.ok(combinations.length > 0, "expected starter combinations");

      const packsDir = join(outputDir, "packs");
      const archives = new Set(
        (await readdir(packsDir)).filter((n) => n.endsWith(".raw.tar.gz")),
      );

      for (const { humanDiscipline, humanTrack } of combinations) {
        const expected = `${getPackName(humanDiscipline, humanTrack)}.raw.tar.gz`;
        assert.ok(
          archives.has(expected),
          `expected packs/${expected} to exist — UI pack-name derivation has drifted from build-packs.js`,
        );
      }
    });

    test("apm install command references an emitted git repo", async () => {
      const packsDir = join(outputDir, "packs");
      const entries = new Set(await readdir(packsDir));
      const { humanDiscipline, humanTrack } = combinations[0];
      const packName = getPackName(humanDiscipline, humanTrack);
      assert.ok(
        entries.has(`${packName}.apm.git`),
        `expected packs/${packName}.apm.git to exist`,
      );
    });

    test("skills git command references an emitted git repo", async () => {
      const packsDir = join(outputDir, "packs");
      const entries = new Set(await readdir(packsDir));
      const { humanDiscipline, humanTrack } = combinations[0];
      const packName = getPackName(humanDiscipline, humanTrack);
      assert.ok(
        entries.has(`${packName}.skills.git`),
        `expected packs/${packName}.skills.git to exist`,
      );
    });

    test("apm unpack command references a real archive", async () => {
      const packsDir = join(outputDir, "packs");
      const archives = new Set(await readdir(packsDir));
      const { humanDiscipline, humanTrack } = combinations[0];

      const command = getApmCommand(
        "https://example.test",
        getPackName(humanDiscipline, humanTrack),
      );
      // The curl portion downloads the archive; extract filename from URL.
      const match = command.match(/\/packs\/([\w-]+\.apm\.tar\.gz)/);
      assert.ok(match, "apm command should reference /packs/<name>.apm.tar.gz");
      assert.ok(
        archives.has(match[1]),
        `apm command references ${match[1]} but packs/ contains: ${[...archives].join(", ")}`,
      );
    });
  });
});
