/**
 * Questions YAML Formatter
 *
 * Formats questions as YAML for export and bulk editing.
 */

import { stringify } from "yaml";

/**
 * Format questions as YAML
 * @param {Object} view - Questions view from prepareQuestionsView
 * @param {Object} options - Format options
 * @returns {string}
 */
/**
 * Build YAML header comment from filter
 * @param {Object} filter
 * @param {number} count - Number of questions
 * @returns {string}
 */
function buildYamlHeader(filter, count) {
  const filterParts = [];
  if (filter.level) filterParts.push(`--level=${filter.level}`);
  if (filter.maturity) filterParts.push(`--maturity=${filter.maturity}`);
  if (filter.skills) filterParts.push(`--skill=${filter.skills.join(",")}`);
  if (filter.behaviours)
    filterParts.push(`--behaviour=${filter.behaviours.join(",")}`);
  if (filter.capability) filterParts.push(`--capability=${filter.capability}`);

  const filterStr =
    filterParts.length > 0 ? filterParts.join(" ") : "(no filters)";
  return `# Generated by: npx fit-pathway questions ${filterStr}\n# Questions: ${count}\n\n`;
}

/**
 * Group questions by source and level into a nested structure
 * @param {Array} questions
 * @returns {Object}
 */
function groupBySourceAndLevel(questions) {
  const bySource = {};
  for (const q of questions) {
    if (!bySource[q.source]) {
      bySource[q.source] = {};
    }
    if (!bySource[q.source][q.level]) {
      bySource[q.source][q.level] = [];
    }

    const yamlQuestion = {
      id: q.id,
      text: q.text,
      lookingFor: q.lookingFor,
      expectedDurationMinutes: q.expectedDurationMinutes,
    };
    if (q.followUps.length > 0) {
      yamlQuestion.followUps = q.followUps;
    }

    bySource[q.source][q.level].push(yamlQuestion);
  }
  return bySource;
}

export function questionsToYaml(view, _options = {}) {
  const { filter, questions } = view;

  const header = buildYamlHeader(filter, questions.length);
  const output = groupBySourceAndLevel(questions);

  // Sort by source ID for stable output
  const sorted = {};
  for (const key of Object.keys(output).sort()) {
    sorted[key] = output[key];
  }

  const yamlContent = stringify(sorted, {
    lineWidth: 80,
    defaultKeyType: "PLAIN",
    defaultStringType: "PLAIN",
  });

  return header + yamlContent;
}
